// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/mesanine/gaffer/event/event.proto

/*
Package event is a generated protocol buffer package.

It is generated from these files:
	github.com/mesanine/gaffer/event/event.proto

It has these top-level messages:
	Event
*/
package event

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Event struct {
	// Optional string matching the ID of a service
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	// EventType
	Type string `protobuf:"bytes,2,opt,name=type" json:"type,omitempty"`
	// Epoch time the event occurred
	Time int64 `protobuf:"varint,3,opt,name=time" json:"time,omitempty"`
	// JSON encoded stats
	Stats []byte `protobuf:"bytes,4,opt,name=stats,proto3" json:"stats,omitempty"`
	// JSON encoded service spec
	Spec []byte `protobuf:"bytes,5,opt,name=spec,proto3" json:"spec,omitempty"`
}

func (m *Event) Reset()                    { *m = Event{} }
func (m *Event) String() string            { return proto.CompactTextString(m) }
func (*Event) ProtoMessage()               {}
func (*Event) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Event) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Event) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Event) GetTime() int64 {
	if m != nil {
		return m.Time
	}
	return 0
}

func (m *Event) GetStats() []byte {
	if m != nil {
		return m.Stats
	}
	return nil
}

func (m *Event) GetSpec() []byte {
	if m != nil {
		return m.Spec
	}
	return nil
}

func init() {
	proto.RegisterType((*Event)(nil), "event.Event")
}

func init() { proto.RegisterFile("github.com/mesanine/gaffer/event/event.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 153 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x24, 0x8d, 0x4d, 0x0a, 0xc2, 0x30,
	0x10, 0x46, 0x49, 0xdb, 0x08, 0x06, 0x71, 0x11, 0x5c, 0x64, 0x59, 0x5c, 0x65, 0x21, 0xcd, 0xc2,
	0x33, 0x78, 0x81, 0xdc, 0x20, 0x6d, 0xa7, 0x75, 0x16, 0xf9, 0xa1, 0x19, 0x05, 0x6f, 0x2f, 0x9d,
	0x6e, 0x86, 0xf7, 0x1e, 0x03, 0x9f, 0x7a, 0xac, 0x48, 0xef, 0xcf, 0x38, 0x4c, 0x39, 0xba, 0x08,
	0x35, 0x24, 0x4c, 0xe0, 0xd6, 0xb0, 0x2c, 0xb0, 0x39, 0xf8, 0x42, 0xa2, 0xe3, 0x0e, 0x65, 0xcb,
	0x94, 0xb5, 0x64, 0xb9, 0xa3, 0x92, 0xaf, 0x1d, 0xf4, 0x55, 0x35, 0x38, 0x1b, 0xd1, 0x0b, 0x7b,
	0xf6, 0x0d, 0xce, 0x5a, 0xab, 0x8e, 0x7e, 0x05, 0x4c, 0xc3, 0x85, 0x99, 0x1b, 0x46, 0x30, 0x6d,
	0x2f, 0x6c, 0xeb, 0x99, 0xf5, 0x4d, 0xc9, 0x4a, 0x81, 0xaa, 0xe9, 0x7a, 0x61, 0x2f, 0xfe, 0x90,
	0xfd, 0xb3, 0x16, 0x98, 0x8c, 0xe4, 0xc8, 0x3c, 0x9e, 0x78, 0xf8, 0xf9, 0x0f, 0x00, 0x00, 0xff,
	0xff, 0x65, 0x02, 0xad, 0x66, 0xa8, 0x00, 0x00, 0x00,
}
