// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/mesanine/gaffer/service/service.proto

/*
Package service is a generated protocol buffer package.

It is generated from these files:
	github.com/mesanine/gaffer/service/service.proto

It has these top-level messages:
	Service
*/
package service

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// A service is a runc application on a host server.
type Service struct {
	Id     string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Bundle string `protobuf:"bytes,2,opt,name=bundle" json:"bundle,omitempty"`
	Spec   []byte `protobuf:"bytes,3,opt,name=spec,proto3" json:"spec,omitempty"`
}

func (m *Service) Reset()                    { *m = Service{} }
func (m *Service) String() string            { return proto.CompactTextString(m) }
func (*Service) ProtoMessage()               {}
func (*Service) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Service) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Service) GetBundle() string {
	if m != nil {
		return m.Bundle
	}
	return ""
}

func (m *Service) GetSpec() []byte {
	if m != nil {
		return m.Spec
	}
	return nil
}

func init() {
	proto.RegisterType((*Service)(nil), "service.Service")
}

func init() { proto.RegisterFile("github.com/mesanine/gaffer/service/service.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 132 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x32, 0x48, 0xcf, 0x2c, 0xc9,
	0x28, 0x4d, 0xd2, 0x4b, 0xce, 0xcf, 0xd5, 0xcf, 0x4d, 0x2d, 0x4e, 0xcc, 0xcb, 0xcc, 0x4b, 0xd5,
	0x4f, 0x4f, 0x4c, 0x4b, 0x4b, 0x2d, 0xd2, 0x2f, 0x4e, 0x2d, 0x2a, 0xcb, 0x4c, 0x4e, 0x85, 0xd1,
	0x7a, 0x05, 0x45, 0xf9, 0x25, 0xf9, 0x42, 0xec, 0x50, 0xae, 0x92, 0x2b, 0x17, 0x7b, 0x30, 0x84,
	0x29, 0xc4, 0xc7, 0xc5, 0x94, 0x99, 0x22, 0xc1, 0xa8, 0xc0, 0xa8, 0xc1, 0x19, 0xc4, 0x94, 0x99,
	0x22, 0x24, 0xc6, 0xc5, 0x96, 0x54, 0x9a, 0x97, 0x92, 0x93, 0x2a, 0xc1, 0x04, 0x16, 0x83, 0xf2,
	0x84, 0x84, 0xb8, 0x58, 0x8a, 0x0b, 0x52, 0x93, 0x25, 0x98, 0x15, 0x18, 0x35, 0x78, 0x82, 0xc0,
	0xec, 0x24, 0x36, 0xb0, 0xb1, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0x00, 0xa4, 0xb5, 0x30,
	0x8a, 0x00, 0x00, 0x00,
}
